### ISSUE TITLE
Errors running the example

### ISSUE THREAD

**Issue by CarlosMoralesSal** [tf-encrypted/tf-seal#51]
Hi, After running any of both examples. I have the next error:

File "logistic_regression.py", line 4, in
import tf_seal as tfs
File "/home/ubuntusystem/Descargas/tf-seal/tf_seal/init.py", line 1, in
from tf_seal.python.tensor import constant
File "/home/ubuntusystem/Descargas/tf-seal/tf_seal/python/tensor.py", line 4, in
import tf_seal.python.ops.seal_ops as ops
File "/home/ubuntusystem/Descargas/tf-seal/tf_seal/python/ops/seal_ops.py", line 5, in
seal_ops = load_library.load_op_library(op_lib_file)
File "/home/ubuntusystem/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntusystem/Descargas/tf-seal/tf_seal/python/ops/_seal_ops.so: cannot open shared object file: No such file or directory

Why?, I have follow every step you have on readme section. Thanks in advance

**Comment by CarlosMoralesSal** [comment]
Hi, After running any of both examples. I have the next error:

  File "logistic_regression.py", line 4, in <module>
    import tf_seal as tfs
  File "/home/ubuntusystem/Descargas/tf-seal/tf_seal/__init__.py", line 1, in <module>
    from tf_seal.python.tensor import constant
  File "/home/ubuntusystem/Descargas/tf-seal/tf_seal/python/tensor.py", line 4, in <module>
    import tf_seal.python.ops.seal_ops as ops
  File "/home/ubuntusystem/Descargas/tf-seal/tf_seal/python/ops/seal_ops.py", line 5, in <module>
    seal_ops = load_library.load_op_library(op_lib_file)
  File "/home/ubuntusystem/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntusystem/Descargas/tf-seal/tf_seal/python/ops/_seal_ops.so: cannot open shared object file: No such file or directory

Why?, I have follow every step you have on readme section. Thanks in advance

**Comment by mortendahl** [comment]
Hi @CarlosMoralesSal, how did you install TF SEAL? Using the pip package or from source? In the latter case, have you first compiled the binary file?

**Comment by CarlosMoralesSal** [comment]
If you mean, run the make in the latter case, yes and I have these errors as well

    `bazel test ... --test_output=all
     Starting local Bazel server and connecting to it...
     ... still trying to connect to local Bazel server after 10 seconds ...
     ... still trying to connect to local Bazel server after 20 seconds ...
     INFO: Call stack for the definition of repository 'local_config_tf' which is a tf_configure (rule 
     definition at /home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl:203:16):
      - /home/ubuntusystem/Descargas/tf-seal/WORKSPACE:32:1 
     ERROR: An error occurred during the fetch of repository 'local_config_tf':
     Traceback (most recent call last):
	File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 178
		_symlink_genrule_for_dir(repository_ctx, tf_header_dir, "incl...", ...")
	File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 150, in _symlink_genrule_for_dir
		_norm_path(src_dir)
	File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 122, in _norm_path
		path[-(1)]
        index out of range (index is -1, but sequence has 0 elements)
        INFO: Call stack for the definition of repository 'remote_java_tools_linux' which is a http_archive (rule definition at  /home/ubuntusystem/.cache/bazel/_bazel_ubuntusystem/27983eb97ba749e7bd2e448e234dfcaa/external/bazel_tools/tools/build_defs/repo/http.bzl:229:16):
         - /DEFAULT.WORKSPACE.SUFFIX:229:1
       ERROR: /home/ubuntusystem/Descargas/tf-seal/tf_seal/BUILD:5:1: no such package '@local_config_tf//': Traceback (most recent call last):
	File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 178
		_symlink_genrule_for_dir(repository_ctx, tf_header_dir, "incl...", ...")
	File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 150, in _symlink_genrule_for_dir
		_norm_path(src_dir)
	File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 122, in _norm_path
		path[-(1)]
        index out of range (index is -1, but sequence has 0 elements) and referenced by '//tf_seal:python/ops/_seal_ops.so'
        ERROR: /home/ubuntusystem/Descargas/tf-seal/tf_seal/BUILD:5:1: no such package '@local_config_tf//': Traceback (most recent call last):
	 File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 178
		_symlink_genrule_for_dir(repository_ctx, tf_header_dir, "incl...", ...")
	 File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 150, in _symlink_genrule_for_dir
		_norm_path(src_dir)
	File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 122, in _norm_path
		path[-(1)]
        index out of range (index is -1, but sequence has 0 elements) and referenced by '//tf_seal:python/ops/_seal_ops.so'
       ERROR: Analysis of target '//tf_seal:seal_ops_py' failed; build aborted: no such package 
       '@local_config_tf//': Traceback (most recent call last):
	    File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 178
		_symlink_genrule_for_dir(repository_ctx, tf_header_dir, "incl...", ...")
	    File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 150, in _symlink_genrule_for_dir
		_norm_path(src_dir)
	    File "/home/ubuntusystem/Descargas/tf-seal/external/tf/tf_configure.bzl", line 122, in _norm_path
		path[-(1)]
           index out of range (index is -1, but sequence has 0 elements)
           INFO: Elapsed time: 33.745s
           INFO: 0 processes.
           FAILED: Build did NOT complete successfully (21 packages loaded, 150 targets c\
           FAILED: Build did NOT complete successfully (21 packages loaded, 150 targets c\
`
Do you mean this?. Thanks

**Comment by justin1121** [comment]
@CarlosMoralesSal can you confirm exactly what your environment looks like, things like: operating system, building tf seal vs. install with pip, docker etc.

I'd recommend also checking the following:

- bazel version 0.26.1 (the docs say >= 0.26.1 but it should probably be changed to ==)
- custom tensorflow build: https://github.com/tf-encrypted/tf-seal#custom-tensorflow install the one depending on your OS

Once that also seems good run:

```
make clean
make build
make test
```

**Comment by CarlosMoralesSal** [comment]
For this case, I have downloaded the git repository and I have done the previous steps, I have created the conda environment, I have downloaded the whl file I have compiled it and then I have done the rest of things. I have the bazel version 0.26,1 and I have done the make things and I have this output

    ` sudo  make build
     TF_NEED_CUDA=0 ./configure.sh
      Using installed tensorflow 
      bazel build build_pip_pkg 
      WARNING: /home/ubuntusystem/.cache/bazel/_bazel_root/27983eb97ba749e7bd2e448e234dfcaa/external/local_config_tf/BUILD:3588:1: target 'libtensorflow_framework.so' is both a rule and a file; please choose another name for the rule
      WARNING: /home/ubuntusystem/.cache/bazel/_bazel_root/27983eb97ba749e7bd2e448e234dfcaa/external/local_config_tf/BUILD:5:12: in hdrs attribute of cc_library rule @local_config_tf//:tf_header_lib: file '_api_implementation.so' from target '@local_config_tf//:tf_header_include' is not allowed in hdrs
      WARNING: /home/ubuntusystem/.cache/bazel/_bazel_root/27983eb97ba749e7bd2e448e234dfcaa/external/local_config_tf/BUILD:5:12: in hdrs attribute of cc_library rule @local_config_tf//:tf_header_lib: file '_message.so' from target '@local_config_tf//:tf_header_include' is not allowed in hdrs
      INFO: Analyzed target //:build_pip_pkg (22 packages loaded, 169 targets configured).
      INFO: Found 1 target...
      INFO: From CcCmakeMakeRule external/seal/lib/include:

      ERROR: /home/ubuntusystem/Descargas/tf-seal/tf_seal/BUILD:5:1: C++ compilation of rule 
      '//tf_seal:python/ops/_seal_ops.so' failed (Exit 1)
       In file included from ./tf_seal/cc/kernels/seal_context.h:11,
                 from tf_seal/cc/kernels/seal_kernels.cc:18:
       ./tf_seal/cc/kernels/seal_helpers.h: In function 'void tf_seal::rotate_sum(seal::Evaluator*, 
       seal::Ciphertext*, const seal::GaloisKeys&)':
       ./tf_seal/cc/kernels/seal_helpers.h:33:21: warning: comparison of integer expressions of different 
       signedness: 'int' and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
      for (int i = 0; i < kPolyModulusDegreePower - 1; i++) {
                   ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     tf_seal/cc/kernels/seal_kernels.cc: In lambda function:
     tf_seal/cc/kernels/seal_kernels.cc:77:71: error: invalid new-expression of abstract class type 
    'tf_seal::Context'
                                                        *context = new Context;
                                                                       ^~~~~~~
     In file included from tf_seal/cc/kernels/seal_kernels.cc:18:
     ./tf_seal/cc/kernels/seal_context.h:25:8: note:   because the following virtual functions are pure 
     within 'tf_seal::Context':
      struct Context : public tensorflow::ResourceBase {
               ^~~~~~~
      In file included from tf_seal/cc/kernels/seal_kernels.cc:7:
      bazel-out/k8- 
      opt/bin/external/local_config_tf/include/tensorflow/core/framework/resource_mgr.h:80:18: note: 	 
      'virtual std::__cxx11::string tensorflow::ResourceBase::DebugString()'
      virtual string DebugString() = 0;
                           ^~~~~~~~~~~
      tf_seal/cc/kernels/seal_kernels.cc: In function 'tensorflow::Status 
      tf_seal::LookupOrCreateWrapper(tensorflow::OpKernelContext*, 
      tensorflow::core::RefCountPtr<tf_seal::Context>*)':
      tf_seal/cc/kernels/seal_kernels.cc:79:55: error: no matching function for call to 
      'LookupOrCreateResource<tf_seal::Context>(tensorflow::OpKernelContext*&, 
      tensorflow::ResourceHandle&, tensorflow::core::RefCountPtr<tf_seal::Context>*&, 
      tf_seal::LookupOrCreateWrapper(tensorflow::OpKernelContext*, 
      tensorflow::core::RefCountPtr<tf_seal::Context>*)::<lambda(auto:4)>)'
                                                      });
                                                       ^
       In file included from tf_seal/cc/kernels/seal_kernels.cc:7: 
       bazel-out/k8- 
       opt/bin/external/local_config_tf/include/tensorflow/core/framework/resource_mgr.h:582:8: note: 
       candidate: 'template<class T> tensorflow::Status 
       tensorflow::LookupOrCreateResource(tensorflow::OpKernelContext*, const 
       tensorflow::ResourceHandle&, T**, std::function<tensorflow::Status(T**)>)'
       Status LookupOrCreateResource(OpKernelContext* ctx, const ResourceHandle& p,
                 ^~~~~~~~~~~~~~~~~~~~~~
       bazel-out/k8- 
       opt/bin/external/local_config_tf/include/tensorflow/core/framework/resource_mgr.h:582:8: note:   
       template argument deduction/substitution failed:
       tf_seal/cc/kernels/seal_kernels.cc:75:65: note:   cannot convert 'context' (type 
       'tensorflow::core::RefCountPtr<tf_seal::Context>*' {aka 'std::unique_ptr<tf_seal::Context, 
        tensorflow::core::RefCountDeleter>*'}) to type 'tf_seal::Context**'
        return tensorflow::LookupOrCreateResource<Context>(ctx, hndl, context,
                                                                              ^~~~~~~
        In file included from bazel-out/k8- 
        opt/bin/external/local_config_tf/include/tensorflow/core/platform/default/logging.h:24,
                       from bazel-out/k8- 
        opt/bin/external/local_config_tf/include/tensorflow/core/platform/logging.h:25,
                      from bazel-out/k8- 
        opt/bin/external/local_config_tf/include/tensorflow/core/lib/core/status.h:25,
                     from bazel-out/k8- 
        opt/bin/external/local_config_tf/include/tensorflow/core/framework/op_def_builder.h:25,
                   from bazel-out/k8- 
        opt/bin/external/local_config_tf/include/tensorflow/core/framework/op.h:23,
                   from tf_seal/cc/kernels/seal_kernels.cc:5:
        tf_seal/cc/kernels/seal_kernels.cc: In instantiation of 'void 
       tf_seal::SealEncryptOp<T>::Compute(tensorflow::OpKernelContext*) [with T = double]':
      tf_seal/cc/kernels/seal_kernels.cc:130:8:   required from here
      tf_seal/cc/kernels/seal_kernels.cc:142:34: warning: comparison of integer expressions of different 
       signedness: 'tensorflow::int64' {aka 'long long int'} and 'size_t' {aka 'long unsigned int'} [-Wsign-compare]
         ctx, input.NumElements() <= kPolyModulusDegree / 2,
                                  ^
          tf_seal/cc/kernels/seal_kernels.cc: In instantiation of 'void 
          tf_seal::SealEncryptOp<T>::Compute(tensorflow::OpKernelContext*) [with T = float]':
          tf_seal/cc/kernels/seal_kernels.cc:130:8:   required from here
          tf_seal/cc/kernels/seal_kernels.cc:142:34: warning: comparison of integer expressions of 
           different signedness: 'tensorflow::int64' {aka 'long long int'} and 'size_t' {aka 'long unsigned 
            int'} [-Wsign-compare]
          Target //:build_pip_pkg failed to build
          Use --verbose_failures to see the command lines of failed build steps.
          INFO: Elapsed time: 96.009s, Critical Path: 87.15s
         INFO: 6 processes: 6 local.
         FAILED: Build did NOT complete successfully
         make: *** [Makefile:37: build] Error 1
      `
Thanks

**Comment by CarlosMoralesSal** [comment]
Problem is close, I had mixed python versions and everything went bad... I unistall everything and just installed python 3.7. I modified the configure file and everything ran.
