### ISSUE TITLE
AttributeError: module 'tf_seal' has no attribute 'convert_to_tensor'

### ISSUE THREAD

**Issue by CarlosMoralesSal** [tf-encrypted/tf-seal#52]
After running the example we can see on the first page of the github, I have this error:
`AttributeError: module 'tf_seal' has no attribute 'convert_to_tensor'`

I'm working with Dockerfile and I have build the docker correctly, but I have this error

I have done the pip install tf-seal but this attribute isn't there, what happen?. I suppose this function should be there, in fact on the code you can find it.

Thanks in advance

**Comment by mortendahl** [comment]
From which directory are you running the example?

**Comment by CarlosMoralesSal** [comment]
I'm trying to run the matmul.py the one you have in examples. Thanks

**Comment by mortendahl** [comment]
Is this still an issue @CarlosMoralesSal?

**Comment by CarlosMoralesSal** [comment]
After compiling everything and doing some changes, everything went well, I had to copy from the baze-bin a .so file to /tf_seal/python/ops/ . The file is _seal_ops.so .So I close the issue

**Comment by mortendahl** [comment]
> I had to copy from the baze-bin a .so file to /tf_seal/python/ops/

This is a result of using Bazel, glad for figured it out!
