### ISSUE TITLE
Trying to work with simple datasets

### ISSUE THREAD

**Issue by CarlosMoralesSal** [tf-encrypted/tf-seal#59]
Hello, I am trying to work with a simple example like this one:
`   
      from __future__ import print_function
      import tensorflow as tf
      from tensorflow.examples.tutorials.mnist import input_data
      mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

    learning_rate = 0.01
    training_epochs = 25
    batch_size = 100
    display_step = 1

     x = tf.placeholder(tf.float32, [None, 784]) # mnist data image of shape 28*28=784
     y = tf.placeholder(tf.float32, [None, 10]) # 0-9 digits recognition => 10 classes

    W = tf.Variable(tf.zeros([784, 10]))
    b = tf.Variable(tf.zeros([10]))

    pred = tf.nn.softmax(tf.matmul(x, W) + b) # Softmax
    cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(pred), reduction_indices=1))
    optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

     init = tf.global_variables_initializer()

     with tf.Session() as sess:
       sess.run(init)
       for epoch in range(training_epochs):
          avg_cost = 0.
          total_batch = int(mnist.train.num_examples/batch_size)
          for i in range(total_batch):
              batch_xs, batch_ys = mnist.train.next_batch(batch_size)
              _, c = sess.run([optimizer, cost], feed_dict={x: batch_xs, y: batch_ys})
              avg_cost += c / total_batch
       
          if (epoch+1) % display_step == 0:
              print("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(avg_cost))

           print("Optimization Finished!")

            correct_prediction = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))
            accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
            print("Accuracy:", accuracy.eval({x: mnist.test.images, y: mnist.test.labels}))`

The example is simple, but it doesn't let me download the dataset. As well, I'm worried because I don't know if tf seal supports this kind of examples.

**Comment by justin1121** [comment]
Hey @CarlosMoralesSal,

I doubt tf-seal would work with this example. It's not yet very sophisticated. I'm not sure why the data won't download though. The example is not currently using tf-seal correct? Might be best to reach out to tensorflow folks for some help or send over the error I can take a quick look.

**Comment by CarlosMoralesSal** [comment]
Hi @justin1121 , I am using the custom tf which you install with the tf seal. After that, I want to start to encrypt data and so on.

**Comment by CarlosMoralesSal** [comment]
This is the error:
    from tensorflow.contrib import cloud
ImportError: cannot import name 'cloud' from 'tensorflow_core.contrib' (/home/carlos/anaconda3/envs/tfseal/lib/python3.7/site-packages/tensorflow_core/contrib/__init__.py)

**Comment by justin1121** [comment]
Looks like the cloud directory isn't included in the pip package that we have prebuilt. Not sure why this is the case. Best bet might be to try building it yourself from https://github.com/tf-encrypted/tf-seal#from-source and seeing if it is included.
