### ISSUE TITLE
Errors on make tensorflow

### ISSUE THREAD

**Issue by CarlosMoralesSal** [tf-encrypted/tf-seal#60]
After doing make tensorflow, I have some errors like these:
    `ERROR: /home/carlos/Descargas/tf-seal/tensorflow-c-17/tensorflow/core/BUILD:2840:1: C++ compilation of rule '//tensorflow/core:framework_internal_impl' failed (Exit 1)
In file included from ./tensorflow/core/framework/register_types.h:22,
                 from tensorflow/core/util/batch_util.cc:18:
./tensorflow/core/framework/variant.h: In member function 'void tensorflow::Variant::HeapOrInline::ResetMemory()':
./tensorflow/core/framework/variant.h:653:45: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'union tensorflow::Variant::HeapOrInline' with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
       this, 0, sizeof(Variant::HeapOrInline));
                                             ^
./tensorflow/core/framework/variant.h:496:9: note: 'union tensorflow::Variant::HeapOrInline' declared here
   union HeapOrInline {
         ^~~~~~~~~~~~
gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2076.649s, Critical Path: 795.15s
INFO: 1011 processes: 1011 local.
FAILED: Build did NOT complete successfully
make: *** [Makefile:52: tensorflow] Error 1
`
What happen?. Just I did a make tensorflow

**Comment by justin1121** [comment]
Looks like you ran out of memory building tensorflow. Not sure how much memory you need but it helps to have a lot.
